package collab

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/Blu3Ph4ntom/warden-mcp/internal/domain"
)

func TestDetermineGitRequirement(t *testing.T) {
	if got := DetermineGitRequirement(WorkflowContext{}); got != GitOptional {
		t.Fatalf("expected optional git requirement, got %s", got)
	}
	ctx := WorkflowContext{MultiOperator: true}
	if got := DetermineGitRequirement(ctx); got != GitRequired {
		t.Fatalf("expected required git integration, got %s", got)
	}
}

func TestValidateSubjectRejectsBrandingAndLongSubjects(t *testing.T) {
	policy := DefaultCommitPolicy()
	issues := policy.ValidateSubject("Generated by Augment for the repo")
	assertHasIssue(t, issues, "COMMIT_SUBJECT_BRANDING")
	issues = policy.ValidateSubject("this subject is intentionally made far too long to fit inside the configured short commit subject rule")
	assertHasIssue(t, issues, "COMMIT_SUBJECT_TOO_LONG")
	issues = policy.ValidateSubject("Add gitignore")
	assertHasIssue(t, issues, "COMMIT_SUBJECT_NOT_LOWERCASE")
	issues = policy.ValidateSubject("add gitignore")
	assertNoErrorIssues(t, issues)
}

func TestInspectRepoReportsAvailabilityHeadAndDirtyState(t *testing.T) {
	dir := t.TempDir()
	state, err := InspectRepo(context.Background(), dir)
	if err != nil {
		t.Fatalf("inspect non-repo: %v", err)
	}
	if state.GitAvailable {
		t.Fatal("expected non-repo directory to report git unavailable")
	}

	runGit(t, dir, "init")
	runGit(t, dir, "config", "user.name", "Warden Test")
	runGit(t, dir, "config", "user.email", "warden@example.com")
	file := filepath.Join(dir, "README.md")
	if err := os.WriteFile(file, []byte("hello\n"), 0o644); err != nil {
		t.Fatalf("write file: %v", err)
	}
	runGit(t, dir, "add", "README.md")
	runGit(t, dir, "commit", "-m", "add readme")

	state, err = InspectRepo(context.Background(), dir)
	if err != nil {
		t.Fatalf("inspect repo: %v", err)
	}
	if !state.GitAvailable || state.Branch == "" || state.Head == "" || state.Dirty {
		t.Fatalf("unexpected clean repo state: %+v", state)
	}

	if err := os.WriteFile(file, []byte("changed\n"), 0o644); err != nil {
		t.Fatalf("rewrite file: %v", err)
	}
	state, err = InspectRepo(context.Background(), dir)
	if err != nil {
		t.Fatalf("inspect dirty repo: %v", err)
	}
	if !state.Dirty {
		t.Fatalf("expected dirty repo state, got %+v", state)
	}
}

func TestDetectStaleStateFindsChangedSignals(t *testing.T) {
	baseline := WorkspaceSnapshot{GitHead: "abc", PlanRevision: 1, MarkdownHash: "hash-a"}
	current := WorkspaceSnapshot{GitHead: "def", PlanRevision: 2, MarkdownHash: "hash-b"}
	signals := DetectStaleState(baseline, current)
	if len(signals) != 3 {
		t.Fatalf("expected 3 stale signals, got %+v", signals)
	}
}

func assertHasIssue(t *testing.T, issues []domain.ValidationIssue, code string) {
	t.Helper()
	for _, issue := range issues {
		if issue.Code == code {
			return
		}
	}
	t.Fatalf("expected issue %s in %+v", code, issues)
}

func assertNoErrorIssues(t *testing.T, issues []domain.ValidationIssue) {
	t.Helper()
	for _, issue := range issues {
		if issue.Severity == "error" {
			t.Fatalf("unexpected error issue: %+v", issue)
		}
	}
}

func runGit(t *testing.T, dir string, args ...string) {
	t.Helper()
	if _, err := gitOutput(context.Background(), dir, args...); err != nil {
		t.Fatalf("git %v failed: %v", args, err)
	}
}
