package collab

import (
	"context"
	"fmt"
	"os/exec"
	"strings"

	"warden-mcp/internal/domain"
)

type GitRequirement string

const (
	GitOptional GitRequirement = "optional"
	GitRequired GitRequirement = "required"
)

var bannedCommitFragments = []string{"generated by", "augment", "auggie", "chatgpt", "claude", "copilot"}

type WorkflowContext struct {
	MultiOperator       bool
	HumanReviewRequired bool
	ArchiveOrRelease    bool
	CrossMachineHandoff bool
}

type CommitPolicy struct {
	MaxSubjectLength int
}

type RepoState struct {
	GitAvailable bool
	Branch       string
	Head         string
	Dirty        bool
	Detached     bool
}

type WorkspaceSnapshot struct {
	GitHead      string
	PlanRevision int
	MarkdownHash string
}

type StaleSignal struct {
	Code    string
	Message string
}

func DetermineGitRequirement(ctx WorkflowContext) GitRequirement {
	if ctx.MultiOperator || ctx.HumanReviewRequired || ctx.ArchiveOrRelease || ctx.CrossMachineHandoff {
		return GitRequired
	}
	return GitOptional
}

func DefaultCommitPolicy() CommitPolicy {
	return CommitPolicy{MaxSubjectLength: 72}
}

func (p CommitPolicy) ValidateSubject(subject string) []domain.ValidationIssue {
	subject = strings.TrimSpace(subject)
	issues := make([]domain.ValidationIssue, 0)
	if subject == "" {
		return append(issues, domain.ValidationIssue{Severity: "error", Code: "COMMIT_SUBJECT_MISSING", Message: "commit subject is required", Path: "subject"})
	}
	if strings.ContainsAny(subject, "\r\n") {
		issues = append(issues, domain.ValidationIssue{Severity: "error", Code: "COMMIT_SUBJECT_MULTILINE", Message: "commit subject must be a single line", Path: "subject"})
	}
	if p.MaxSubjectLength <= 0 {
		p.MaxSubjectLength = DefaultCommitPolicy().MaxSubjectLength
	}
	if len(subject) > p.MaxSubjectLength {
		issues = append(issues, domain.ValidationIssue{Severity: "error", Code: "COMMIT_SUBJECT_TOO_LONG", Message: fmt.Sprintf("commit subject must be %d characters or fewer", p.MaxSubjectLength), Path: "subject"})
	}
	lower := strings.ToLower(subject)
	for _, fragment := range bannedCommitFragments {
		if strings.Contains(lower, fragment) {
			issues = append(issues, domain.ValidationIssue{Severity: "error", Code: "COMMIT_SUBJECT_BRANDING", Message: "commit subject must not include generated branding or tool signatures", Path: "subject"})
			break
		}
	}
	if subject != lower {
		issues = append(issues, domain.ValidationIssue{Severity: "warning", Code: "COMMIT_SUBJECT_NOT_LOWERCASE", Message: "lowercase subjects are preferred", Path: "subject"})
	}
	if strings.HasSuffix(subject, ".") {
		issues = append(issues, domain.ValidationIssue{Severity: "warning", Code: "COMMIT_SUBJECT_TRAILING_PUNCTUATION", Message: "trailing punctuation is discouraged", Path: "subject"})
	}
	return issues
}

func InspectRepo(ctx context.Context, dir string) (RepoState, error) {
	if _, err := gitOutput(ctx, dir, "rev-parse", "--is-inside-work-tree"); err != nil {
		return RepoState{}, nil
	}
	branch, err := gitOutput(ctx, dir, "rev-parse", "--abbrev-ref", "HEAD")
	if err != nil {
		return RepoState{}, err
	}
	head, err := gitOutput(ctx, dir, "rev-parse", "--verify", "HEAD")
	if err != nil {
		head = ""
	}
	status, err := gitOutput(ctx, dir, "status", "--porcelain")
	if err != nil {
		return RepoState{}, err
	}
	return RepoState{GitAvailable: true, Branch: branch, Head: head, Dirty: strings.TrimSpace(status) != "", Detached: branch == "HEAD"}, nil
}

func DetectStaleState(baseline, current WorkspaceSnapshot) []StaleSignal {
	signals := make([]StaleSignal, 0)
	if baseline.GitHead != "" && current.GitHead != "" && baseline.GitHead != current.GitHead {
		signals = append(signals, StaleSignal{Code: "GIT_HEAD_CHANGED", Message: "git head changed since baseline"})
	}
	if baseline.PlanRevision > 0 && current.PlanRevision > 0 && baseline.PlanRevision != current.PlanRevision {
		signals = append(signals, StaleSignal{Code: "PLAN_REVISION_CHANGED", Message: "plan revision changed since baseline"})
	}
	if baseline.MarkdownHash != "" && current.MarkdownHash != "" && baseline.MarkdownHash != current.MarkdownHash {
		signals = append(signals, StaleSignal{Code: "MARKDOWN_HASH_CHANGED", Message: "markdown projection changed since baseline"})
	}
	return signals
}

func gitOutput(ctx context.Context, dir string, args ...string) (string, error) {
	cmd := exec.CommandContext(ctx, "git", args...)
	cmd.Dir = dir
	output, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("git %s: %w: %s", strings.Join(args, " "), err, strings.TrimSpace(string(output)))
	}
	return strings.TrimSpace(string(output)), nil
}
